project:
  type: website

website:
  title: "Gianluca Rigoletti's Blog"
  comments:
    giscus:
      repo: grigolet/blog-comments
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/grigolet
      - icon: twitter
        href: https://twitter.com/gianrigoletti
format:
  html:
    theme: zephyr
    css: styles.css



