project:
  type: website
  output-dir: docs
website:
  title: "G.R.'s Blog"
  site-url: https://grigolet.github.io
  description: "Gianluca Rigoletti's blog about data analysis, visualization and sometimes cooking."
  twitter-card: true
  open-graph: true
  image: "profile.png"
  comments:
    giscus:
      repo: grigolet/blog-comments
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/grigolet
      - icon: twitter
        href: https://twitter.com/gianrigoletti
      - icon: rss
        href: index.xml
format:
  html:
    theme: zephyr
    css: styles.css
    code-line-numbers: true




